import React, { useState, useEffect } from 'react';
import api from '../services/api';
import { 
  BookOpen, ChevronDown, ChevronUp, Copy, Check, 
  Brain, AlertCircle, Info, Tag, Bookmark, BookmarkCheck,
  Download, Highlighter, BookOpenCheck, RefreshCw
} from 'lucide-react';

const Notes = () => {
  const [notes, setNotes] = useState([]);
  const [phase, setPhase] = useState('loading'); // loading | notes | error
  const [weekInfo, setWeekInfo] = useState({ currentWeek: 1, weekGoal: '' });
  const [error, setError] = useState('');
  
  // Custom interactive features
  const [expandedTopic, setExpandedTopic] = useState(0);
  const [copiedSection, setCopiedSection] = useState(null); // 'summary-index' etc.
  const [bookmarkedTopics, setBookmarkedTopics] = useState(() => {
    const saved = localStorage.getItem('notes_bookmarks');
    return saved ? JSON.parse(saved) : {};
  });
  const [readTopics, setReadTopics] = useState(() => {
    const saved = localStorage.getItem('notes_read');
    return saved ? JSON.parse(saved) : {};
  });
  const [highlightMode, setHighlightMode] = useState(false);
  const [showBookmarksOnly, setShowBookmarksOnly] = useState(false);

  const fetchNotes = async () => {
    setPhase('loading');
    setError('');
    try {
      const res = await api.post('/ai/notes');
      if (res.data?.notes) {
        setNotes(res.data.notes);
        setWeekInfo({ currentWeek: res.data.currentWeek || 1, weekGoal: res.data.weekGoal || '' });
        setPhase('notes');
        if (res.data.notes.length > 0) setExpandedTopic(0);
      } else {
        throw new Error('Invalid notes structure received.');
      }
    } catch (err) {
      setError(err.response?.data?.message || err.message || 'Failed to generate study notes. Please try again.');
      setPhase('error');
    }
  };

  useEffect(() => {
    fetchNotes();
  }, []);

  // Save Bookmarks to localStorage
  useEffect(() => {
    localStorage.setItem('notes_bookmarks', JSON.stringify(bookmarkedTopics));
  }, [bookmarkedTopics]);

  // Save Read status to localStorage
  useEffect(() => {
    localStorage.setItem('notes_read', JSON.stringify(readTopics));
  }, [readTopics]);

  const copyToClipboard = (text, key) => {
    navigator.clipboard.writeText(text);
    setCopiedSection(key);
    setTimeout(() => setCopiedSection(null), 2000);
  };

  const toggleBookmark = (idx) => {
    setBookmarkedTopics(prev => ({
      ...prev,
      [idx]: !prev[idx]
    }));
  };

  const toggleReadStatus = (idx) => {
    setReadTopics(prev => ({
      ...prev,
      [idx]: !prev[idx]
    }));
  };

  // Markdown Export Function
  const exportNotesMarkdown = () => {
    let md = "# AI Study Notes — Week " + weekInfo.currentWeek + "\n";
    md += "## Goal: " + (weekInfo.weekGoal || "Learning Curriculum Objectives") + "\n\n";
    md += "*Generated by PathPilot AI Learning roadmap generator*\n\n---\n\n";

    notes.forEach((note, idx) => {
      md += "### Topic " + (idx + 1) + ": " + note.topic + "\n\n";
      md += "#### Summary\n" + note.summary + "\n\n";
      
      md += "#### Key Points\n";
      note.key_points.forEach(pt => {
        md += "- " + pt + "\n";
      });
      md += "\n";

      if (note.important_terms && note.important_terms.length > 0) {
        md += "#### Important Terms\n";
        md += note.important_terms.map(t => String.fromCharCode(96) + t + String.fromCharCode(96)).join(', ') + "\n\n";
      }

      if (note.examples && note.examples.length > 0) {
        md += "#### Examples & Code snippets\n";
        note.examples.forEach((ex, eIdx) => {
          md += "##### Example " + (eIdx + 1) + "\n" + String.fromCharCode(96) + String.fromCharCode(96) + String.fromCharCode(96) + "javascript\n" + ex + "\n" + String.fromCharCode(96) + String.fromCharCode(96) + String.fromCharCode(96) + "\n\n";
        });
      }
      md += "---\n\n";
    });

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', "PathPilot_StudyNotes_Week" + weekInfo.currentWeek + ".md");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Compute Reading progress percentage
  const totalNotesCount = notes.length;
  const readNotesCount = Object.values(readTopics).filter(Boolean).length;
  const readingProgress = totalNotesCount > 0 ? Math.round((readNotesCount / totalNotesCount) * 100) : 0;

  // Filter notes based on toggle
  const displayedNotes = showBookmarksOnly 
    ? notes.map((n, idx) => ({ ...n, originalIdx: idx })).filter(n => bookmarkedTopics[n.originalIdx])
    : notes.map((n, idx) => ({ ...n, originalIdx: idx }));

  // ── LOADING ──
  if (phase === 'loading') {
    return (
      <div className="flex flex-col items-center justify-center h-96 space-y-4">
        <div className="relative h-20 w-20 flex items-center justify-center rounded-full bg-accent/10">
          <BookOpen className="h-10 w-10 text-accent dark:text-blue-400 animate-pulse" />
          <div className="absolute inset-0 rounded-full border-4 border-accent border-t-transparent animate-spin" />
        </div>
        <div className="text-center">
          <h3 className="font-bold text-slate-800 dark:text-white">Writing Study Notes</h3>
          <p className="text-xs text-slate-400 mt-1 animate-pulse">Organising concepts, definitions, and code snippets for you…</p>
        </div>
      </div>
    );
  }

  // ── ERROR ──
  if (phase === 'error') {
    return (
      <div className="flex flex-col items-center justify-center h-96 space-y-4">
        <AlertCircle className="h-12 w-12 text-red-500" />
        <div className="text-center">
          <h3 className="font-bold text-slate-800 dark:text-white">Failed to Load Notes</h3>
          <p className="text-xs text-slate-405 mt-1">{error}</p>
        </div>
        <button onClick={fetchNotes} className="flex items-center space-x-2 rounded-xl bg-accent text-white px-5 py-2.5 text-sm font-bold shadow-md hover:bg-blue-700 transition-colors">
          <RefreshCw className="h-4 w-4" />
          <span>Try Again</span>
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-6 max-w-7xl">
      {/* Header Banner */}
      <div className="rounded-2xl bg-gradient-to-r from-accent to-secondary p-6 text-white shadow-xl flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div className="flex items-center space-x-3">
          <span className="flex h-12 w-12 items-center justify-center rounded-xl bg-white/10 text-white">
            <Brain className="h-7 w-7" />
          </span>
          <div>
            <h1 className="text-2xl font-extrabold">AI Study Notes</h1>
            <p className="text-indigo-100 text-xs mt-0.5">Week {weekInfo.currentWeek} Goal: {weekInfo.weekGoal || 'Master current topics'}</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {/* Highlighter toggle */}
          <button 
            onClick={() => setHighlightMode(!highlightMode)}
            className={"flex items-center space-x-1.5 rounded-xl px-4 py-2.5 text-xs font-bold transition-all shadow-sm border " + (highlightMode ? "bg-yellow-500 text-white border-yellow-400" : "bg-white text-slate-705 border-slate-205 dark:bg-darkbg-card dark:border-slate-800 dark:text-slate-300 hover:bg-slate-50")}
            title="Toggle Highlight Mode"
          >
            <Highlighter className="h-4 w-4" />
            <span className="hidden sm:inline">Highlight Assist</span>
          </button>
          
          {/* Download Markdown notes */}
          <button 
            onClick={exportNotesMarkdown}
            className="flex items-center space-x-1.5 rounded-xl bg-white text-slate-700 border border-slate-200 px-4 py-2.5 text-xs font-bold transition-all shadow-sm hover:bg-slate-50 dark:bg-darkbg-card dark:border-slate-800 dark:text-slate-300"
            title="Download Notes as Markdown"
          >
            <Download className="h-4 w-4" />
            <span className="hidden sm:inline">Download MD</span>
          </button>
        </div>
      </div>

      {/* Reading Progress Bar */}
      <div className="rounded-2xl bg-white p-5 border border-slate-100 dark:bg-darkbg-card dark:border-darkbg-border shadow-sm space-y-2">
        <div className="flex items-center justify-between text-xs font-bold text-slate-400">
          <span className="flex items-center space-x-1">
            <BookOpenCheck className="h-4.5 w-4.5 text-accent" />
            <span>Reading Progress</span>
          </span>
          <span className="font-mono text-accent">{readingProgress}% Done ({readNotesCount}/{totalNotesCount} Topics)</span>
        </div>
        <div className="h-2 w-full rounded-full bg-slate-100 dark:bg-slate-800 overflow-hidden">
          <div 
            className="h-full bg-gradient-to-r from-accent to-secondary rounded-full transition-all duration-500" 
            style={{ width: readingProgress + "%" }}
          ></div>
        </div>
      </div>

      {/* 12-Column Responsive Layout */}
      <div className="grid gap-6 lg:grid-cols-12 items-start">
        
        {/* Table of Contents (3 Columns) */}
        <nav className="lg:col-span-3 sticky top-24 space-y-4">
          <div className="rounded-2xl bg-white p-4 border border-slate-100 dark:bg-darkbg-card dark:border-darkbg-border shadow-sm">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100 dark:border-slate-800/80">
              <h3 className="font-bold text-slate-805 dark:text-white text-xs uppercase tracking-wider">Table of Contents</h3>
              <span className="text-[10px] bg-slate-100 dark:bg-slate-805 dark:text-slate-400 font-bold px-2 py-0.5 rounded-full">{displayedNotes.length} Items</span>
            </div>

            {/* Filter Bookmark Toggle */}
            <div className="mt-3">
              <button 
                onClick={() => setShowBookmarksOnly(!showBookmarksOnly)}
                className={"w-full py-1.5 px-3 rounded-lg border text-[10px] font-bold transition-all text-center flex items-center justify-center space-x-1.5 " + (showBookmarksOnly ? "bg-amber-500/10 text-amber-600 border-amber-500/20" : "bg-slate-50 border-slate-200 text-slate-555 hover:text-slate-700 dark:bg-slate-900/40 dark:border-slate-800 dark:text-slate-400 dark:hover:text-slate-205")}
              >
                <Bookmark className={"h-3 w-3 " + (showBookmarksOnly ? "fill-current" : "")} />
                <span>{showBookmarksOnly ? "Showing Bookmarks" : "Show Bookmarked Only"}</span>
              </button>
            </div>

            <ul className="mt-3.5 space-y-1.5 max-h-[320px] overflow-y-auto pr-1">
              {displayedNotes.map((note) => (
                <li key={note.originalIdx}>
                  <button
                    onClick={() => {
                      setExpandedTopic(note.originalIdx);
                      document.getElementById("topic-card-" + note.originalIdx)?.scrollIntoView({ behavior: 'smooth', block: 'center' });
                    }}
                    className={"w-full text-left py-2 px-3 rounded-xl text-xs font-semibold flex items-center justify-between transition-all duration-200 " + (expandedTopic === note.originalIdx ? "bg-accent/10 text-accent dark:bg-accent/15 dark:text-blue-400" : "text-slate-555 hover:bg-slate-50 dark:text-slate-400 dark:hover:bg-slate-900/30")}
                  >
                    <span className="truncate pr-2">{note.topic}</span>
                    <div className="flex items-center space-x-1 flex-shrink-0">
                      {bookmarkedTopics[note.originalIdx] && <Bookmark className="h-3 w-3 text-amber-500 fill-current" />}
                      {readTopics[note.originalIdx] && <span className="text-[10px] text-green-500">✓</span>}
                    </div>
                  </button>
                </li>
              ))}
              {displayedNotes.length === 0 && (
                <p className="text-[10px] text-slate-405 text-center py-4">No notes match bookmarks filter.</p>
              )}
            </ul>
          </div>
        </nav>

        {/* Main Scrollable Notes List (9 Columns) */}
        <div className="lg:col-span-9 space-y-5">
          {displayedNotes.map((note) => {
            const isExpanded = expandedTopic === note.originalIdx;
            const isBookmarked = !!bookmarkedTopics[note.originalIdx];
            const isRead = !!readTopics[note.originalIdx];

            return (
              <div 
                key={note.originalIdx}
                id={"topic-card-" + note.originalIdx}
                className={"rounded-2xl bg-white dark:bg-darkbg-card border shadow-sm overflow-hidden transition-all duration-300 " + (isExpanded ? "border-accent/40 dark:border-accent/30 shadow-md ring-1 ring-accent/5" : "border-slate-100 dark:border-slate-800")}
              >
                {/* Topic Accordion Header */}
                <div className="w-full flex items-center justify-between p-5 text-left bg-slate-50/50 dark:bg-slate-900/10">
                  <div className="flex items-center space-x-3.5 min-w-0 flex-1 cursor-pointer" onClick={() => setExpandedTopic(isExpanded ? null : note.originalIdx)}>
                    <span className={"flex h-8 w-8 items-center justify-center rounded-lg font-bold text-xs flex-shrink-0 transition-colors " + (isRead ? "bg-success/15 text-success animate-pulse" : "bg-indigo-50 text-indigo-600 dark:bg-indigo-950/40 dark:text-indigo-400")}>
                      {isRead ? "✓" : note.originalIdx + 1}
                    </span>
                    <h3 className="text-sm font-bold text-slate-800 dark:text-white truncate">{note.topic}</h3>
                  </div>

                  {/* Bookmark, Checkbox, Toggle Buttons */}
                  <div className="flex items-center space-x-2.5 ml-4 flex-shrink-0">
                    {/* Read Status Switch */}
                    <button 
                      onClick={() => toggleReadStatus(note.originalIdx)}
                      className={"p-1.5 rounded-lg border transition-all " + (isRead ? "bg-green-50 border-green-200 text-green-600 dark:bg-green-955/20 dark:border-green-905/35 dark:text-green-400" : "bg-white border-slate-205 text-slate-400 hover:text-slate-600 hover:bg-slate-50 dark:bg-darkbg dark:border-slate-800")}
                      title={isRead ? "Mark as Unread" : "Mark as Read"}
                    >
                      <BookOpenCheck className="h-4 w-4" />
                    </button>

                    {/* Bookmark Switch */}
                    <button 
                      onClick={() => toggleBookmark(note.originalIdx)}
                      className={"p-1.5 rounded-lg border transition-all " + (isBookmarked ? "bg-amber-50 border-amber-205 text-amber-500 dark:bg-amber-955/20 dark:border-amber-900/35" : "bg-white border-slate-205 text-slate-400 hover:text-slate-600 hover:bg-slate-50 dark:bg-darkbg dark:border-slate-800")}
                      title={isBookmarked ? "Remove Bookmark" : "Bookmark Note"}
                    >
                      {isBookmarked ? <BookmarkCheck className="h-4 w-4 fill-current text-amber-555" /> : <Bookmark className="h-4 w-4" />}
                    </button>

                    {/* Expand Trigger */}
                    <button
                      onClick={() => setExpandedTopic(isExpanded ? null : note.originalIdx)}
                      className="p-1 rounded text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800"
                    >
                      {isExpanded ? <ChevronUp className="h-5 w-5" /> : <ChevronDown className="h-5 w-5" />}
                    </button>
                  </div>
                </div>

                {/* Collapsible Content */}
                {isExpanded && (
                  <div className="p-6 space-y-6 border-t border-slate-100 dark:border-darkbg-border divide-y divide-slate-100 dark:divide-darkbg-border">
                    
                    {/* Summary */}
                    <div className="space-y-2">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center space-x-1.5 text-xs font-bold text-slate-405 uppercase tracking-wider">
                          <Info className="h-4.5 w-4.5 text-indigo-500" />
                          <span>Summary</span>
                        </div>
                        <button
                          onClick={() => copyToClipboard(note.summary, "summary-" + note.originalIdx)}
                          className="text-slate-400 hover:text-slate-655 dark:hover:text-white p-1 rounded transition-colors"
                          title="Copy Summary"
                        >
                          {copiedSection === "summary-" + note.originalIdx ? <Check className="h-4 w-4 text-green-500" /> : <Copy className="h-4 w-4" />}
                        </button>
                      </div>
                      <p className={"text-xs text-slate-605 dark:text-slate-350 leading-relaxed font-medium " + (highlightMode ? "bg-yellow-500/10 dark:bg-yellow-500/5 px-2.5 py-1.5 rounded-lg border border-yellow-500/20" : "")}>
                        {note.summary}
                      </p>
                    </div>

                    {/* Key Points */}
                    <div className="pt-6 space-y-3">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center space-x-1.5 text-xs font-bold text-slate-400 uppercase tracking-wider">
                          <BookOpen className="h-4.5 w-4.5 text-purple-500" />
                          <span>Key Points</span>
                        </div>
                        <button
                          onClick={() => copyToClipboard(note.key_points.join('\n'), "keypoints-" + note.originalIdx)}
                          className="text-slate-400 hover:text-slate-655 dark:hover:text-white p-1 rounded transition-colors"
                          title="Copy Key Points"
                        >
                          {copiedSection === "keypoints-" + note.originalIdx ? <Check className="h-4 w-4 text-green-500" /> : <Copy className="h-4 w-4" />}
                        </button>
                      </div>
                      <ul className="space-y-2">
                        {note.key_points.map((pt, idx) => (
                          <li key={idx} className="flex items-start text-xs text-slate-600 dark:text-slate-300 leading-relaxed">
                            <span className="h-1.5 w-1.5 rounded-full bg-indigo-500 mt-2 mr-2.5 flex-shrink-0" />
                            <span className={highlightMode && idx % 2 === 0 ? "bg-yellow-500/15 dark:bg-yellow-500/5 px-1 py-0.5 rounded" : ""}>{pt}</span>
                          </li>
                        ))}
                      </ul>
                    </div>

                    {/* Important Terms */}
                    {note.important_terms && note.important_terms.length > 0 && (
                      <div className="pt-6 space-y-3">
                        <div className="flex items-center space-x-1.5 text-xs font-bold text-slate-400 uppercase tracking-wider">
                          <Tag className="h-4.5 w-4.5 text-pink-500" />
                          <span>Key Terms</span>
                        </div>
                        <div className="flex flex-wrap gap-2">
                          {note.important_terms.map((term, idx) => (
                            <span 
                              key={idx}
                              className="inline-flex items-center rounded-lg bg-slate-50 border border-slate-200 px-2.5 py-1 text-[10px] font-bold text-slate-600 dark:bg-slate-900/50 dark:border-slate-800 dark:text-slate-400"
                            >
                              {term}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Code Examples */}
                    {note.examples && note.examples.length > 0 && (
                      <div className="pt-6 space-y-3">
                        <div className="flex items-center space-x-1.5 text-xs font-bold text-slate-400 uppercase tracking-wider">
                          <Brain className="h-4.5 w-4.5 text-green-500" />
                          <span>Examples & Practice</span>
                        </div>
                        <div className="space-y-3.5">
                          {note.examples.map((ex, idx) => {
                            const isCode = ex.includes('const ') || ex.includes('function ') || ex.includes('import ') || ex.includes('class ') || ex.includes('{') || ex.includes('||');
                            return (
                              <div key={idx} className="rounded-xl border border-slate-100 dark:border-slate-800 overflow-hidden shadow-xs">
                                <div className="flex items-center justify-between px-4 py-2 bg-slate-50/50 dark:bg-slate-900/30 border-b border-slate-100 dark:border-slate-800">
                                  <span className="text-[10px] font-bold text-slate-450">Example {idx + 1}</span>
                                  <button
                                    onClick={() => copyToClipboard(ex, "ex-" + note.originalIdx + "-" + idx)}
                                    className="text-slate-400 hover:text-slate-600 dark:hover:text-white p-1 rounded transition-colors"
                                    title="Copy Example"
                                  >
                                    {copiedSection === "ex-" + note.originalIdx + "-" + idx ? <Check className="h-3.5 w-3.5 text-green-500" /> : <Copy className="h-3.5 w-3.5" />}
                                  </button>
                                </div>
                                <div className="p-4 bg-slate-50/10 dark:bg-slate-900/10">
                                  {isCode ? (
                                    <pre className="text-[11px] font-mono text-slate-700 dark:text-slate-300 overflow-x-auto leading-relaxed whitespace-pre-wrap">
                                      {ex}
                                    </pre>
                                  ) : (
                                    <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed font-medium">
                                      {ex}
                                    </p>
                                  )}
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      </div>
                    )}

                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default Notes;